# Generated by Django 5.1.4 on 2024-12-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_inscripcion_taller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion_taller',
            name='estado',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
    ]
