# Generated by Django 5.1.4 on 2024-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_inscripcion_taller_estado_delete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='Taller'),
        ),
    ]
