# Generated by Django 5.1.3 on 2024-11-25 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adulto_Mayor',
            fields=[
                ('adulto_mayor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_taller',
            fields=[
                ('clasificacion_taller_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('taller_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cupo_maximo', models.IntegerField()),
                ('clasificacion_taller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clasificacion_taller')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor')),
                ('sala_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_material',
            fields=[
                ('registro_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_utilizada', models.IntegerField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_taller',
            fields=[
                ('inscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('adulto_mayor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.adulto_mayor')),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_especial',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_evento', models.DateField()),
                ('taller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateField()),
                ('contenido', models.TextField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Funcionario_municipal',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('administrador_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
    ]
