# Generated by Django 4.2.9 on 2024-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='fotos_perfil/'),
        ),
    ]
