# Generated by Django 4.2.9 on 2024-11-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default='default_username', max_length=50, unique=True),
        ),
    ]
