# Generated by Django 4.2.9 on 2024-11-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
    ]
