# Generated by Django 5.1.3 on 2024-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='funcionario_municipal',
            name='usuario_id',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
