# Generated by Django 5.1.3 on 2024-12-03 02:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_comentario_remove_reporte_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='dias',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
