# Generated by Django 5.1.3 on 2024-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_taller_dias_taller_hora_fin_taller_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='dias',
            field=models.DateField(),
        ),
    ]
