# Generated by Django 5.1.3 on 2024-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_taller_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='dias',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=50),
        ),
    ]
