# Generated by Django 5.1.3 on 2024-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_taller_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_taller',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inscripcion_taller',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
