# Generated by Django 5.1.4 on 2024-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='image',
            field=models.ImageField(blank=True, default='predeterminada.jpeg', null=True, upload_to='Taller'),
        ),
    ]
